USE [INVENTORY]
GO

/****** Object:  Table [dbo].[TBL_CART_ITEMS]    Script Date: 03-09-2015 03:26:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TBL_CART_ITEMS](
	[TRANSACTION_ID] [int] IDENTITY(1,1) NOT NULL,
	[BILL_ID] [int] NOT NULL,
	[PRODUCT_NAME] [varchar](50) NOT NULL,
	[QUANTITY] [int] NOT NULL,
	[TOTAL_PRODUCT_AMOUNT] [int] NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


USE [INVENTORY]
GO

/****** Object:  Table [dbo].[TBL_CATAGORY]    Script Date: 03-09-2015 03:26:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TBL_CATAGORY](
	[CATAGORY_ID] [int] IDENTITY(1,1) NOT NULL,
	[CATAGORY_NAME] [varchar](50) NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


USE [INVENTORY]
GO

/****** Object:  Table [dbo].[TBL_MAIN_BILL]    Script Date: 03-09-2015 03:27:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TBL_MAIN_BILL](
	[BILL_ID] [int] IDENTITY(1,1) NOT NULL,
	[CUSTOMER_NAME] [varchar](50) NULL,
	[BILL_DATE] [datetime] NOT NULL,
	[TOTAL_ITEMS] [int] NOT NULL,
	[TOTAL_AMOUNT_PAID] [int] NOT NULL,
	[PREPARED_BY] [varchar](50) NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TBL_MAIN_BILL] ADD  CONSTRAINT [DF_TBL_MAIN_BILL_BILL_DATE]  DEFAULT (getdate()) FOR [BILL_DATE]
GO




USE [INVENTORY]
GO

/****** Object:  Table [dbo].[TBL_STOCK]    Script Date: 03-09-2015 03:27:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TBL_STOCK](
	[PRODUCT_ID] [int] IDENTITY(1,1) NOT NULL,
	[PRODUCT_CATAGORY] [varchar](50) NOT NULL,
	[PRODUCT_NAME] [varchar](50) NOT NULL,
	[PRODUCT_QUANTITY] [int] NOT NULL,
	[PRODUCT_PRICE] [int] NOT NULL,
	[STOCK_DATE] [date] NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TBL_STOCK] ADD  CONSTRAINT [DF_TBL_STOCK_STOCK_DATE]  DEFAULT (getdate()) FOR [STOCK_DATE]
GO


USE [INVENTORY]
GO
/****** Object:  Table [dbo].[TBL_USER_TABLE]    Script Date: 09/03/2015 17:55:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TBL_USER_TABLE](
	[SERIAL_ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[USER_TYPE] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[PASSWORD] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 CONSTRAINT [PK_USER_TABLE] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF